/**
 * Default Open Graph image used across all pages.
 * The image is dynamically generated by src/app/opengraph-image.tsx
 */
export const DEFAULT_OG_IMAGES = [
  {
    url: "https://rvtowingcalc.com/opengraph-image",
    width: 1200,
    height: 630,
    alt: "RV Towing Calculator - Tow Safe. Tow Smart.",
  },
];
